SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE* S.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS S
JOIN PRODUCT AS P ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE