SELECT E.ID,
CASE 
 WHEN E.SIZE_RANK = 1 THEN 'CRITICAL'
 WHEN E.SIZE_RANK = 2 THEN 'HIGH'
 WHEN E.SIZE_RANK = 3 THEN 'MEDIUM'
 ELSE 'LOW' END AS COLONY_NAME
 FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK FROM ECOLI_DATA ) AS E
ORDER BY E.ID