SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(AVG(R.REVIEW_SCORE),2) as score
FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
order by AVG(R.REVIEW_SCORE) DESC, I.FAVORITES DESC