SELECT B.CATEGORY AS CATEGORY, SUM(S.SALES) AS SALES
FROM BOOK_SALES AS S
JOIN BOOK AS B ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;